# Generated by Django 6.0.7 on 2026-08-26 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='detections/%Y/%m/%d/')),
                ('predicted_class', models.CharField(max_length=255)),
                ('confidence', models.FloatField(default=0.0)),
                ('model_name', models.CharField(default='YOLO11 Classification', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detection History',
                'verbose_name_plural': 'Detection Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
