# Generated by Django 6.0.7 on 2026-08-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionhistory',
            name='detection_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('camera', 'Live Camera')], default='image', max_length=20),
        ),
        migrations.AddField(
            model_name='detectionhistory',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='detection_videos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='detectionhistory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='detections/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='detectionhistory',
            name='predicted_class',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
