# Generated by Django 6.0.7 on 2026-08-26 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, default='profile_images/default.png', null=True, upload_to='profile_images/')),
                ('cover_image', models.ImageField(blank=True, default='cover_images/default_cover.jpg', null=True, upload_to='cover_images/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('division', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('profession', models.CharField(blank=True, max_length=150)),
                ('organization', models.CharField(blank=True, max_length=150)),
                ('website', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True, help_text='Separate skills with commas.')),
                ('facebook', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('portfolio', models.URLField(blank=True)),
                ('language', models.CharField(choices=[('English', 'English'), ('Bangla', 'Bangla')], default='English', max_length=20)),
                ('theme', models.CharField(choices=[('Light', 'Light'), ('Dark', 'Dark'), ('System', 'System')], default='System', max_length=20)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('ai_alerts', models.BooleanField(default=True)),
                ('weekly_reports', models.BooleanField(default=True)),
                ('public_profile', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
