# Generated by Django 6.0.7 on 2026-08-27 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
